# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IHGtFOGMozBP8MSIC9Fl_l3zm88FF4Hy
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
dataset=pd.read_csv('/content/housing.csv')
dataset.head(n=10)